version: '3.8'

services:
  client:
    build:
      target: development
      context: ./client
    ports:
      - 3172:3172
    environment:
      - NODE_ENV=development
      - TEST_MODE=false
    volumes:
      - ./client:/app
      - /app/node_modules
