version: '3.8'

services:
  client:
    depends_on:
      - backend
    build:
      target: development
      context: ./client
    ports:
      - 3172:3172
    environment:
      - NODE_ENV=development
      - TEST_MODE=false
    volumes:
      - ./client:/app
      - /app/node_modules

  backend:
    build:
      target: development
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - /app/.venv
      - /app/__pycache__
      - /app/.pytest_cache
