name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_build_client:
    name: 'Test Build Client (CI)'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Set up .env file'
        working-directory: 'client/'
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "GUILD_ID=${{ secrets.GUILD_ID }}" >> .env
          echo "TEST_MODE=true" >> .env

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: client
          push: false
          tags: discord-bot:ci-test
          target: development
          platforms: linux/amd64
          file: client/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker

      - name: 'Test login'
        run: docker run --rm discord-bot:ci-test
